server:
  port: 8080

spring:
  datasource:
    username: root
    password: 243698
    #url: jdbc:mysql://localhost:3306/mymall
    url: jdbc:mysql://localhost:3306/bookalone?rewirteBatchedStatements=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
